name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          echo "GIT_TAG=`$(git describe --tags --abbrev=0|sed s/^v//g)`" >> $GITHUB_ENV
          docker login --username jmedin1965 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/jmedin1965/firefox-java-vnc-flash-base:latest --tag ghcr.io/jmedin1965/firefox-java-vnc-flash-base:${{ vars.GIT_TAG }}
          docker push ghcr.io/jmedin1965/firefox-java-vnc-flash-base:latest
          docker push ghcr.io/jmedin1965/firefox-java-vnc-flash-base:${{ vars.GIT_TAG }}
