name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on:  ubuntu-latest
    steps:
      -
        name: GIT Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Get git tag using little-core-labs/get-git-tag
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName
        with:
          tagRegex: "(.*)"
      -
        name: Get git tag
        run: |
          echo "GIT_TAG=$(set -- $(grep -e '^#\s\+[0-9]\+\.[0-9]\+\.[0-9]\+\s*$' CHANGELOG.md | head -n 1); echo $2)" >> $GITHUB_ENV
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      -
        name: Build and push the image
        run: |
          echo "the value is GIT_TAG:       $GIT_TAG"
          echo "the value is GIT_TAG_NAME:  $GIT_TAG_NAME"
          echo "the value is GIT_TAG_NAME:  ${{ steps.tagName.outputs.tag }}"
#          docker build . --tag ghcr.io/jmedin1965/firefox-java-vnc-flash-base:latest --tag "ghcr.io/jmedin1965/firefox-java-vnc-flash-base:$GIT_TAG"
#          docker push "ghcr.io/jmedin1965/firefox-java-vnc-flash-base:latest"
#          docker push "ghcr.io/jmedin1965/firefox-java-vnc-flash-base:$GIT_TAG"
