name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get git tag
        run: |
          echo "from file = $(set -- $(grep -e '^#\s\+[0-9]\+\.[0-9]\+\.[0-9]\+\s*$' CHANGELOG.md | head -n 1); echo $2)"
          echo "tag=${{steps.tagger.outputs.tag}}"
          echo "GIT_TAG=$(git describe --tags --abbrev=0|sed s/^v//g)"
          echo "GIT_TAG=aabbcc" >> $GITHUB_ENV
          echo "GIT_TAG2=$(git describe --tags --abbrev=0|sed s/^v//g)" >> $GITHUB_ENV
          echo "GIT_TAG3=$(set -- $(grep -e '^#\s\+[0-9]\+\.[0-9]\+\.[0-9]\+\s*$' CHANGELOG.md | head -n 1); echo $2)" >> $GITHUB_ENV
          ls
          pwd
      - name: Build and push the image
        run: |
          echo "the value is GIT_TAG:  $GIT_TAG"
          echo "the value is GIT_TAG2: $GIT_TAG2"
          echo "the value is GIT_TAG3: $GIT_TAG3"
