name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on:  ubuntu-latest
    steps:
      -
        name: GIT Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Get git --tags --abrev=0 to env GIT_TAG
        run: |
          echo "GIT_TAG=$(git describe --tags --abbrev=0 | sed s/[v]*//g)" >> $GITHUB_ENV
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      -
        name: Build and push the image
        run: |
          echo "the value is GIT_TAG:       $GIT_TAG"
          docker build . --tag ghcr.io/jmedin1965/firefox-java-vnc-flash-base:latest --tag "ghcr.io/jmedin1965/firefox-java-vnc-flash-base:$GIT_TAG"
          docker push "ghcr.io/jmedin1965/firefox-java-vnc-flash-base:latest"
          docker push "ghcr.io/jmedin1965/firefox-java-vnc-flash-base:$GIT_TAG"
