name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get git tag
        run: |
          echo "GIT_TAG=$(git describe --tags --abbrev=0|sed s/^v//g)"
          echo "GIT_TAG=aabbcc" >> $GITHUB_ENV
          echo "GIT_TAG2=$(git describe --tags --abbrev=0|sed s/^v//g)" >> $GITHUB_ENV
      - name: Build and push the image
        run: |
          echo "the value is GIT_TAG:  $GIT_TAG"
          echo "the value is GIT_TAG2: $GIT_TAG2"
