name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get git tag
        run: |
          echo "GIT_TAG=$(set -- $(grep -e '^#\s\+[0-9]\+\.[0-9]\+\.[0-9]\+\s*$' CHANGELOG.md | head -n 1); echo $2)" >> $GITHUB_ENV
      - name: Build and push the image
        run: |
          echo "the value is GIT_TAG:  $GIT_TAG"
          docker login --username jmedin1965 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/jmedin1965/firefox-java-vnc-flash-base:latest --tag "ghcr.io/jmedin1965/firefox-java-vnc-flash-base:$GIT_TAG"
          docker push ghcr.io/jmedin1965/firefox-java-vnc-flash-base:latest
          docker push "ghcr.io/jmedin1965/firefox-java-vnc-flash-base:$GIT_TAG"
